apiVersion: v1
kind: Service
metadata:
  name: {{ template "myapp.name" . }}
  labels:
    app: {{ template "myapp.name" . }}
    environment: {{ .Values.environment | default "dev" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ template "myapp.name" . }}
